### PR TITLE
COE-813-oee-simulators-fix-issue-that-no-profiles-is-generated-on-new-cumulocity-version-10-16

### PR DESCRIPTION
**Pull request by namnhatpham**

### CODE REVIEW

**Comment by MarkJMReynolds-SAG** [comment]
Did create a build based on this PR @ https://github.com/SoftwareAG/oee-simulators/actions/runs/3903928177

**Review by mvoigt-sag — APPROVED** [review]
@MarkJMReynolds-SAG did you test the build that you created on a 10.16 C8Y ?

**Comment by MarkJMReynolds-SAG** [comment]
@mvoigt-sag Only on my own tenant at https://reynolds.latest.stage.c8y.io/, which appears to be a 10.16/17 hybrid.

**Review by mvoigt-sag — APPROVED** [review]
tested with build https://github.com/SoftwareAG/oee-simulators/actions/runs/3903928177 on https://mynewtenantfromworkflow.pm-1017-oee.stage.c8y.io/apps/devicemanagement/index.html#/device

**Pull request merged**
