### PR TITLE
COE-908: Add strict_mode which will stop the script automatically when issue happen

### PR DESCRIPTION
**Pull request by namnhatpham**
https://cumulocity.atlassian.net/browse/COE-908

### CODE REVIEW

**Review by MarkJMReynolds-SAG — COMMENTED** [review]
Looks like it would do what I would be after, nice 👍 
Needs some attention to fix the failing checks before I would approve, though.

**Comment by namnhatpham** [comment]
> Looks like it would do what I would be after, nice 👍 Needs some attention to fix the failing checks before I would approve, though.



> Looks like it would do what I would be after, nice 👍 Needs some attention to fix the failing checks before I would approve, though.

I ran the test manually on my tenant (Nam environment) and it passed the tests. The failed checks happened because oee-dev environment doesn't have measurements or alarms at the test period

**Comment by mvoigt-sag** [comment]
> > Looks like it would do what I would be after, nice 👍 Needs some attention to fix the failing checks before I would approve, though.
> 
> > Looks like it would do what I would be after, nice 👍 Needs some attention to fix the failing checks before I would approve, though.
> 
> I ran the test manually on my tenant (Nam environment) and it passed the tests. The failed checks happened because oee-dev environment doesn't have measurements or alarms at the test period

well, maybe we need to make sure to have the prerequisites properly setup before running the test? e.g. we could create the required measurements or alarms within the test setup...

**Comment by MarkJMReynolds-SAG** [comment]
@mvoigt-sag Apologies for the delay, didn't get a notification for some reason... 😕 

Yes, IMHO something like that should 100% be part of a new PR. If for some reason you need to revert/fix the strict_mode related stuff, you'd still want to have your tests available.

**Comment by mvoigt-sag** [comment]
@namnhatpham can you please check the test errors again? maybe it would work now with the latest changes from the develop branch?

**Comment by namnhatpham** [comment]
> @namnhatpham can you please check the test errors again? maybe it would work now with the latest changes from the develop branch?

The fix for this errors was made in another branch and merged to the main so I just need to merge it back here to solve the issue

**Pull request merged**
